name: Build Plugins

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.x

      - run: dotnet restore --locked-mode

      - run: dotnet build --configuration Release --no-restore

      - uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: OkxPlugin\x64\Release\OkxPlugin.dll
