name: Build Plugins

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.1'

      - run: msbuild -m -t:Restore -p:Configuration=Release -p:Platform="Any CPU"

      - run: msbuild -m -t:Build -p:Configuration=Release -p:Platform="Any CPU"

      - uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: OkxPlugin\x64\Release\OkxPlugin.dll
