name: Build Plugins

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1.1

      - run: msbuild /t:restore

      - run: msbuild /t:build RainmeterPlugin.sln /p:Configuration=Release /p:Platform="Any CPU"

      - uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: OkxPlugin\x64\Release\OkxPlugin.dll
