name: Build Plugins

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - run: msbuild RainmeterPlugin.sln -t:rebuild /p:Platform="Any CPU" /p:Configuration=Release

      - uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: OkxPlugin\x64\Release\OkxPlugin.dll
